@url = https://nitc-mess.herokuapp.com
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTU3M2E0MGM1Y2RhMTAwMDQ0YjZjMDQiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJ0ZXN0IiwiZXhwIjoxNTg4MDUzMDI4LjE1NSwiaWF0IjoxNTgyODY5MDI4fQ.Y_uhYXyDnz6321nOAcXz9P9VR-zrWxlPImKhIKfb64U"
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTJiYWNmMjEzOGI1NTAwMDRhZmYzNjIiLCJyb2xlIjoiYWRtaW4iLCJuYW1lIjoiYWRtaW4iLCJleHAiOjE1ODUxNTExNzcuOTkxLCJpYXQiOjE1Nzk5NjcxNzd9.6OM5JUpjHDOqrEEBI_TFjVfmwZ1M9X3kmrEJucNIUQk
###
# API 
###
POST {{url}}/api/auth/signup
Content-Type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "password": "12345",
    "rollNumber" : "B100000EC"
}

###
POST {{url}}/api/auth/signin
Content-Type: application/json

{
    "email": "f_hostel@nitc.ac.in",
    "password": "f_hostel@nitc.ac.in"
}


###

POST {{url}}/api/auth/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345"
}

###
GET {{url}}/api/users/me
Authorization: Bearer {{token}}

###
GET {{url}}/api/users/dues
Authorization: Bearer {{token}}

### 
POST {{url}}/api/dues/add
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "b180913Cs",
    "message": "Juice", 
    "amount": 80
}
###
DELETE {{url}}/api/dues/delete
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "_id": "5e2af5997e17082947798dd6"
}

###
GET {{url}}/api/dues/list
Authorization: Bearer {{adminToken}}
Content-Type: application/json


###
POST {{url}}/api/admin/assign-mess
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "B180288CS",
    "mess": "P2"
}

###
GET {{url}}/api/admin/list-people-without-mess
Authorization: Bearer {{adminToken}}

###
DELETE {{url}}/api/admin/remove-from-mess
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "rollNumber": "B180288CS"
}
